// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_template/test/app/features/login/presentation/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_template/app/shared/core/error/failures/failures.dart'
    as _i1;
import 'package:flutter_template/app/shared/core/result/result.dart' as _i3;
import 'package:flutter_template/app/shared/domain/repositories/authentication_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<ReturnType, ErrorType extends _i1.Failure>
    extends _i2.SmartFake implements _i3.Result<ReturnType, ErrorType> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i2.Mock
    implements _i4.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<void, _i1.Failure>> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i5.Future<_i3.Result<void, _i1.Failure>>.value(
            _FakeResult_0<void, _i1.Failure>(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Result<void, _i1.Failure>>);
}
