include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_child_properties_last: true
analyzer:
  errors:
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
  exclude:
    - generated/**
