name: flutter_template
description: starting template for a flutter project
version: 1.0.0+0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  dart_ping: ^8.0.1
  dart_ping_ios: ^3.0.0
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.4
  flutter_template_api:
    path: ./generated/api
  formz: ^0.6.0
  get_it: ^7.2.0
  go_router: ^6.5.2
  google_fonts: ^4.0.4
  intl: ^0.18.0
  pigeon: ^10.1.6
  shared_preferences: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
