// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by NativeSideApi.
NSObject<FlutterMessageCodec> *NativeSideApiGetCodec(void);

@protocol NativeSideApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)callNativeSideWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void NativeSideApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NativeSideApi> *_Nullable api);

/// The codec used by FlutterSideApi.
NSObject<FlutterMessageCodec> *FlutterSideApiGetCodec(void);

@interface FlutterSideApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)callFlutterAppError:(nullable NSString *)error completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
