// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeSideApi {
  func callNativeSide() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeSideApiSetup {
  /// The codec used by NativeSideApi.
  /// Sets up an instance of `NativeSideApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeSideApi?) {
    let callNativeSideChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_template.NativeSideApi.callNativeSide", binaryMessenger: binaryMessenger)
    if let api = api {
      callNativeSideChannel.setMessageHandler { _, reply in
        do {
          let result = try api.callNativeSide()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      callNativeSideChannel.setMessageHandler(nil)
    }
  }
}
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FlutterSideApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  func callFlutterApp(error errorArg: String?, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_template.FlutterSideApi.callFlutterApp", binaryMessenger: binaryMessenger)
    channel.sendMessage([errorArg] as [Any?]) { _ in
      completion()
    }
  }
}
