// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_template/test/app/features/login/data/login_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_template/app/shared/core/api/api_manager.dart' as _i2;
import 'package:flutter_template/app/shared/data/data_sources/authentication_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiManager_0 extends _i1.SmartFake implements _i2.ApiManager {
  _FakeApiManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationDataSource extends _i1.Mock
    implements _i3.AuthenticationDataSource {
  MockAuthenticationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiManager get apiManager => (super.noSuchMethod(
        Invocation.getter(#apiManager),
        returnValue: _FakeApiManager_0(
          this,
          Invocation.getter(#apiManager),
        ),
      ) as _i2.ApiManager);
  @override
  _i4.Future<String> login(
    String? id,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            id,
            password,
          ],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}
